
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export PATH="$HOME/Library/Haskell/bin:$PATH"
export P4PORT="ssl:perforce.savagebeast.com:1666"
export P4CLIENT="caldrich-laptop"
#export P4CLIENT="caldrich-integ"

HISTFILESIZE=10000000

# aliases
alias vi='vim'
alias ebp='vim ~/.zshrc && source ~/.zshrc'
alias t='trash'
alias f='find . -name'
alias sl='ls'
alias rm='rm -i'
alias ssh='sshrc'

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="bullet-train"
BULLETTRAIN_PROMPT_CHAR='λ'

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi
