configuration:
  brew:
    packages:
      - 'python3'
      - 'trash-cli'
    cask:
      - 'atom',
      - 'chrome',
      - '1password',
      - 'dropbox'
  atom:
    packages:
      - 'vim-mode-plus'
      - 'ex-mode'
