configuration:
  brew:
    packages:
      - 'python3'
      - 'trash-cli'
    casks:
      - 'atom'
      - 'google-chrome'
      - '1password'
      - 'dropbox'
      - 'firefox'
  atom:
    packages:
      - 'vim-mode-plus'
      - 'ex-mode'
