# Path to your oh-my-zsh installation.
export ZSH=/Users/chetaldrich/.oh-my-zsh

# Aliases
alias up='cd ..'
alias busy='cat /dev/urandom | hexdump -C | grep "ca fe"'
alias ebp='vim ~/.zshrc && source ~/.zshrc'
alias dfl='cd ~/dotfiles'
alias c='cd ~/code'
alias f='find . -name'
alias sl='ls'
alias t=trash
alias rm='rm -i'

# Git related aliases

# goes to root of git repo
alias gt='cd $(git rev-parse --show-toplevel)'
# edits gitignore at root of git repo
alias gi='vim $(git rev-parse --show-toplevel)/.gitignore'

# Default user for zsh themes
DEFAULT_USER='chetaldrich'

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=10

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(python git brew autojump bower)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin"
export PATH="$HOME/Library/Haskell/bin:$PATH"

# autojump configuration 
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh  ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

